### PR TITLE
Show line numbers and allow jumping to specific lines in job logs

### PR DESCRIPTION
**Pull request by punchagan**
This PR adds some simple JS and CSS to allow jumping to a specific line number in the logs, and also displays line numbers for all logs

A URL like `http://localhost:8080/job/2022-02-09/115753-docker-build-71c777#L11-L15` would highlight lines 11 to 15 and scroll the page to line 11. 
image

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Could there be a special tag name for the last line as well by any chance?

**Comment by kit-ty-kate** [comment]
> Some thing like `#end` always takes you to the last line of the log?

yes, that would be perfect! Thanks!

**Comment by punchagan** [comment]
@art-w pointed out that the log response would be streamed by the server and this JS code wouldn't behave correctly when the output has not yet been completely rendered. I'll take a look into how to do this correctly and update the PR.

**Comment by punchagan** [comment]
I've updated the PR to use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to update the line numbers being displayed in the logs, as the logs get streamed from the server.

**Comment by punchagan** [comment]
> > Some thing like `#end` always takes you to the last line of the log?
> 
> yes, that would be perfect! Thanks!

I've also added a commit that always scrolls the page to the end when `#end` URL hash is present.

**Comment by punchagan** [comment]
@talex5 @tmcgilchrist could you please review this PR?

**Comment by punchagan** [comment]
Thanks @tmcgilchrist !

**Pull request merged**
