### PR TITLE
Add a lock file

### PR DESCRIPTION
**Pull request by samoht**
Generated using `opam monorepo lock`.

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Can you say a bit more about why we need this? @samoht

**Comment by maiste** [comment]
With the development cycle of `ocurrent` a lock file might be a too strong constraint.
Should we close this PR?

**Comment by tmcgilchrist** [comment]
I think so. The original issue was about getting a working opam switch /
dune build. Maybe just confirm the instructions on how to do that still
work.

**Comment by maiste** [comment]
Today the opam switch is working and dune build to do I'm closing it.

**Pull request closed without merging**
