### PR TITLE
Github PRs: pulling labels

### PR DESCRIPTION
**Pull request by ElectreAAS**
This PR allows `pr_info` to hold label information.

### CODE REVIEW

**Review by maiste — COMMENTED** [review]
Thanks for the PR! That's a nice to have. Could you please add an entry to the [CHANGES.md](https://github.com/ocurrent/ocurrent/blob/master/CHANGES.md) file?

**Comment by ElectreAAS** [comment]
> Thanks for the PR! That's a nice to have. Could you please add an entry to the [CHANGES.md](https://github.com/ocurrent/ocurrent/blob/master/CHANGES.md) file?

Yes, done!

**Comment by maiste** [comment]
> @maiste do you think that we should also provide the label color, along with its name ?

Not sure that it brings valuable information... However, if you think it can be useful in one of the ocurrent projects, no problem to add it. In this case, it should be an associative list with `(string * color) list`.

The use case I see is to tweak the behaviour in the function of the labels, not the colour. WDYT?

**Review by TheLortex — APPROVED** [review]

**Comment by maiste** [comment]
Wait for the CI to goes green before merging :)

**Pull request merged**
